name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build
      
    - name: Get short SHA
      id: sha
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: chicker94/hello:${{ env.SHORT_SHA }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  update-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get short SHA
      id: sha
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Checkout CD repository
      uses: actions/checkout@v4
      with:
        repository: chicker94/fleet-cd-test
        ref: main
        ssh-key: ${{ secrets.CD_REPO_SSH_KEY }}
        
    - name: Update Kubernetes manifest
      run: |
        sed -i "s|chicker94/hello:[a-zA-Z0-9]*|chicker94/hello:${{ env.SHORT_SHA }}|" simple/manifests/deployments/hello.yaml
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git add simple/manifests/deployments/hello.yaml
        git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
        git push

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582